// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWnTJo0XA0i-BJZXNevtIvd2PRT2Snj0g',
    appId: '1:1092007640680:web:d75b0d4fa3878e0eddc5dd',
    messagingSenderId: '1092007640680',
    projectId: 'restaurantfinder-b04a0',
    authDomain: 'restaurantfinder-b04a0.firebaseapp.com',
    storageBucket: 'restaurantfinder-b04a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO-l92OEKSUumZJetWLYnsknv_MC3bM98',
    appId: '1:1092007640680:android:fff688877a1be9ecddc5dd',
    messagingSenderId: '1092007640680',
    projectId: 'restaurantfinder-b04a0',
    storageBucket: 'restaurantfinder-b04a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTugot63p4dmu0KI_ZoewGFINKOQWhIjA',
    appId: '1:1092007640680:ios:7a2e96ebb3d0a236ddc5dd',
    messagingSenderId: '1092007640680',
    projectId: 'restaurantfinder-b04a0',
    storageBucket: 'restaurantfinder-b04a0.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTugot63p4dmu0KI_ZoewGFINKOQWhIjA',
    appId: '1:1092007640680:ios:7a2e96ebb3d0a236ddc5dd',
    messagingSenderId: '1092007640680',
    projectId: 'restaurantfinder-b04a0',
    storageBucket: 'restaurantfinder-b04a0.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWnTJo0XA0i-BJZXNevtIvd2PRT2Snj0g',
    appId: '1:1092007640680:web:65c5ca1cd58802bcddc5dd',
    messagingSenderId: '1092007640680',
    projectId: 'restaurantfinder-b04a0',
    authDomain: 'restaurantfinder-b04a0.firebaseapp.com',
    storageBucket: 'restaurantfinder-b04a0.firebasestorage.app',
  );
}
